SSINS/Catalog_Plot.py

This just makes the default INS plots less cluttered for observations with more than 1 pol

Change default figure size for INS_Plot

---

SSINS/Catalog_Plot.py

The logic has been changed so that the model_func variable is evaluated independently for pre_model and post_model. Previously if either of these was set to True, the model_func variable was set to SS.mixture_prob, regardless of whether one was set to False. 
The individual if blocks that plot the pre and post-flagged data now have if statements that ask whether model_func should be set to None or SS.mixture_prob. This decouples the logic.
What cannot be done is a post_flag model when only plotting pre_flagged data, which could be of interest to some.

Vdh plot logic

---

SSINS/match_filter.py
SSINS/tests/test_MF.py

Using safe_dump when there are streak events in the match filter did not work since slice(None).start is an object. This branch makes the slice_dict of the match filter explicitly set a slice for the whole band instead of using slice(None).

Handle streak slices more carefully

---

SSINS/incoherent_noise_spectrum.py

It seems the earlier bug was not fixed by the previous change (although it was a good change). This change actually fixes the bug, which is that a numpy.int64 cannot be written into a yaml file using safe_dump.

convert slice bounds to int on write

---

SSINS/match_filter.py
SSINS/tests/test_MF.py
docs/tutorial.rst

This lets the user pass a single number for the threshold, similar to old functionality, so that users do not need to change their scripts if they do not want to take advantage of the new multi-threshold functionality.

Sig thresh dict back compat

---

SSINS/incoherent_noise_spectrum.py
SSINS/tests/test_MF.py

This makes match_event files writable when samp_thresh events are found.

Handle Nonetype sig_thresh

---

Scripts/MWA_EoR_High_Flag.py

This PR adds three settings to the script, two of which are mostly conveniences and the third of which is topical to the `occ_csv.py` script.
* `-v --verbose` toggles conout of completed files and the total time elapsed once finished
* `-p --plots` toggles generation of plots (which cause a ~10x slowdown in total completion time)
* `-g --gencsv` toggles generation of a csv file `occcsv.csv` for occ_csv.py; if a file exists there it is wiped automatically 
Also, the description for -w is substantially changed since plots are seperate option now.

add -v/-p/-g options to highflag script

---

SSINS/sky_subtract.py
SSINS/tests/test_INS.py
SSINS/tests/test_SS.py
SSINS/tests/test_plot.py
docs/tutorial.rst

This change sets the default behavior of `diff` to `False` in `SS.read`. It issues a warning for cases where this is relevant. Unit tests to check diff'd data have been added. This was causing a bug when multiple files were being read in simultaneously, since `UVData.read` calls itself recursively in that case, and `SS.read` overrides `UVData.read`. This was leading to the first set of integrations begin differenced _twice_.

Diff def false

---

scripts/MWA_EoR_High_Flag.py

This pull request uses python's `multiprocessing` pool to multithread the task of creating output graphs. To do this, the meat of the processing has been moved to a function `execbody` (the different indentation of which has caused a large line change count).
A new command line option, ~~`-t`/`--threads`~~ sets the number of objects in the pool to thread. The default is for four threads; more should be used if available. This is now handled with `-n`/`--numthreads` as `-t` means something else on the occ_csv script. The script prints out the type of threading it is using (SP/MP execution path) and additionally prints the number of threads used if the number of cores is >=2.
Additionally, the -g option now requires a filename and no longer hardcodes an output file.

add multiprocessing support to highflag script

---

SSINS/incoherent_noise_spectrum.py
SSINS/sky_subtract.py
SSINS/tests/test_INS.py
SSINS/tests/test_SS.py
scripts/Run_HERA_SSINS.py

This small PR just ensures that the SS data array is masked when necessary. Previously, if diff() was not called on read, the data_array would not get masked and issues would happen when initializing INS objects. Now, there is a quick check on initialization and an application of a mask if one is missing.

Mask when essential

---

SSINS/incoherent_noise_spectrum.py
SSINS/tests/test_INS.py
SSINS/tests/test_MF.py
docs/tutorial.rst

This PR let's SSINS use the nsample_array and integration_time attributes of an SS (UVData) object in order to do a weighted incoherent average, with the correct z-scores.

Weighted Incoherent Average

---

SSINS/tests/test_plot.py

This adds some calls to pytest.importorskip that marks tests to be skipped if matplotlib cannot be imported, so that people without matplotlib can run the unit tests.

Add importorskip calls

---

SSINS/tests/test_util.py
SSINS/util.py
scripts/Run_HERA_SSINS.py

This PR adds a utility function that allows for combining INS that have been calculated for different baseline subsets within an observation. Since an INS has no exact concept of which baselines actually contributed, only the number that contributed to each sample, there is no check to confirm that different baseline subsets being combined are actually exclusive to one another. However, there are checks to make sure that the time, frequency, and polarization arrays match.

Add Combining INS of different baseline subsets

---

CHANGELOG.md
SSINS/incoherent_noise_spectrum.py
SSINS/tests/test_INS.py

This PR gives a keyword `inplace` to select that when True does the select inplace on the INS object (default) or when False, returns a copy of the selected object without touching the original object.

Select inplace

---

setup.py

Fixes error thrown by installation with yaml. Changes the way SSINS defines its version so that SSINS can be installed without importing all its requirements
The yaml lines below give an error message (also below). This would be fixed by switching to using `setuptools_scm`, but this hotfix takes care of the problem for now.
``` 
- pip:
- -e ./repos/pyuvdata
- -e ./repos/SSINS
```
```
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: / Ran pip subprocess with arguments:
['/home/azureuser/miniconda3/envs/azure/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/azureuser/condaenv.z7fp8qls.requirements.txt']
Pip subprocess output:
Obtaining …
```

import error hotfix

---

CHANGELOG.md
SSINS/sky_subtract.py
SSINS/tests/test_INS.py
SSINS/tests/test_SS.py
SSINS/tests/test_plot.py
SSINS/tests/test_util.py

This PR puts some pytest warning filters in the test suite so that the user is not blasted with superfluous warnings while running tests.

Warnings markers

---

SSINS/sky_subtract.py

This pull request approximately doubles the speed of the diff() function in sky_subtract.
The original diff() function calls pyuvdata's safe data grabbing functions to get data to diff. However, the dataset is already put in baseline form, which ensures that the data's ordering is known, and therefore the overhead of these functions is not necessary. As a result, the new diff() is somewhat more than twice as fast as the old one (according to my machine [E5 2440 v2 @1.9 Ghz] and cProfile).
The new implementation of diff starts by allocating two indexing arrays which copy the baseline array. By differencing the baseline array between adjacent members, and knowing that the array is in baseline form, it can be seen that the only nonzero members of the array are at boundaries between different …

Optimize differencing in  time

---

.gitignore
SSINS/__init__.py
setup.py

This PR changes how the version information is generated and saved in SSINS to be more robust and flexible. Previously, it seemed that a local installation with `pip install -e .` was required so that the package could query the git status of the repo on package import, but this change allows for the repo to be installed anywhere. The version information is generated by `setuptools_scm` on package setup and written to `SSINS/version.py`, which is then used to set the package's `__version__` attribute.
The biggest difference is that the `branch_scheme` for `setuptools_scm` from pyuvdata is no longer imported from the package, but has instead been copied to `setup.py`. This was required so that the version information could be generated without adding pyuvdata as a setup dependency, which …

Change how version information is generated

---

CHANGELOG.md
SSINS/Catalog_Plot.py

This is a simple fix where I just ensured that the `xscale` kwarg was being passed into `hist_plot` from `VDH_plot`. Closes #108 

pipe xscale kwarg to hist_plot

---

CHANGELOG.md
SSINS/sky_subtract.py
SSINS/tests/test_SS.py

This is a quick PR to always call SS.apply_flags after SS.diff, since they are basically never executed without one another, and in fact SS.apply_flags is required in order for a diff'd object to be passed to INS.
See general summary

Call apply flags after diff

---

CHANGELOG.md
SSINS/tests/test_SS.py

Change a unit test so that it is more flexible with pyuvdata version
For some currently unknown reason, pyuvdata 2.2.8 reads one of the test files in with its first antenna number being 0, while pyuvdata 2.2.9 reads it in with it being equal to 1. This was causing a unit test to fail since the requested antpairs in a downselect were hard coded. The hard code was able to be removed while preserving the spirit of the test.

Change antpair request in unit test

---

CHANGELOG.md
SSINS/Catalog_Plot.py
SSINS/plot_lib.py
SSINS/tests/test_SS.py
SSINS/tests/test_plot.py
docs/tutorial.rst

Redo a few things in the plotting code to avoid using deprecated matplotlib functionality. Would close #105 
matplotlib warns against using FixedFormatter for ticks without using FixedLocator. Even though it's never been a problem so far, I've made the plotting code explicitly use FixedLocator when using FixedFormatter (which is implicitly called when handing e.g. set_xticklabels a list or other sequence). It also warns against modifying the globally registered colormap. I've thus made all colormap alternations operate on a copy of the global cmap object. 

Plot revamp

---

.github/workflows/testsuite.yml
.readthedocs.yml
CHANGELOG.md
README.md
SSINS/incoherent_noise_spectrum.py
SSINS/tests/test_INS.py
SSINS/tests/test_MF.py
SSINS/tests/test_SS.py
SSINS/tests/test_plot.py
SSINS/tests/test_util.py
ci/SSINS_tests.yml
docs/conf.py
docs/rtd-env.yml

There is an issue with the windows builds probably related to astropy, see #114 The goal is to bring this from failing to passing using better unit tests.
TODO LIST

Fix windows failing builds by making better unit test architecture

---

.github/workflows/testsuite.yml
SSINS/incoherent_noise_spectrum.py
SSINS/sky_subtract.py
SSINS/tests/test_INS.py
SSINS/tests/test_SS.py
SSINS/tests/test_util.py
docs/conftest.py
docs/tutorial.rst

This fixes several things that will break for pyuvdata>=v3.0, including going to future shapes always.
I made some minor tweaks to the GitHub actions yaml to speed up CI.

Fix a SSINS test for future pyuvdata compatibility

---

.github/workflows/testsuite.yml
SSINS/incoherent_noise_spectrum.py
SSINS/tests/test_INS.py
SSINS/tests/test_SS.py
ci/SSINS_tests.yml
pyproject.toml

Karto is working a major refactoring of `select` across all the pyuvdata classes (https://github.com/RadioAstronomySoftwareGroup/pyuvdata/pull/1523). The changes to UVFlag caused errors in the SSINS CI job.
The new code does the select by using the UVParameter form information to ensure that all arrays are properly selected. This broke the selection for the SSINS `metric_ms` and `sig_array` because those were not UVParameter objects.
This PR makes them UVParameters and tweaks some related code to make everything work properly. All the tests pass, but this is a significant change, so it's possible something about this breaks things in a subtle way that isn't covered by tests, so please take a careful look.
I also fixed a test that was writing a test file to my local SSINS directory and …

Fixes to ensure future pyuvdata compatibility

---

.github/workflows/testsuite.yml
CHANGELOG.md
README.md
SSINS/incoherent_noise_spectrum.py
SSINS/sky_subtract.py
SSINS/tests/test_INS.py
SSINS/tests/test_SS.py
SSINS/tests/test_util.py
ci/SSINS_tests.yml
pyproject.toml

This cleans up a bunch of warnings in the tests, along with some related changes. 
It also essentially abandons passing the `use_future_array_shapes` kwarg into the pyuvdata reading functions because pyuvdata does not support these. It will still pop the kwarg before reading, in case someone passed it in with old code. I have updated the pyuvdata requirements accordingly.
- [x ] Add or update docstring related to code change
- [x ] Add a unit test that verifies the efficacy of the code
- [x ] Update CHANGELOG.md

Warning cleanup
