SSINS/incoherent_noise_spectrum.py
SSINS/match_filter.py
SSINS/tests/test_INS.py

This change has been implemented, tested in anger, and is covered by unit tests locally. Need to see if Travis passes.

Get polyfit

---

SSINS/incoherent_noise_spectrum.py
SSINS/tests/test_INS.py
docs/tutorial.rst

This allows one to write mwaf files when the resolutions of the SSINS data and the original mwaf files do not match.

Mwaf robust

---

SSINS/Catalog_Plot.py
SSINS/incoherent_noise_spectrum.py
SSINS/match_filter.py
SSINS/plot_lib.py
SSINS/tests/test_MF.py
SSINS/tests/test_plot.py
SSINS/tests/test_util.py
SSINS/util.py
Scripts/significance_record.py

This adds a script that plots a record of the significances that different data were caught at during flagging, as well as the iteration they were flagged in. It also makes the default behavior of Catalog_Plot.INS to make these plots if there are events that were caught during flagging.

Sig scripts

---

SSINS/incoherent_noise_spectrum.py

This changes pyyaml to use safe_dump and safe_write

Yaml update

---

Scripts/Run_HERA_SSINS.py

This just adds a script that I tested does work.

Run hera ssins script

---

.travis.yml
README.md
SSINS/incoherent_noise_spectrum.py
SSINS/sky_subtract.py

This enforces an assumption that SSINS makes about the data array of the visibility file - namely that it is in time-baseline order.

Use blt order check

---

SSINS/incoherent_noise_spectrum.py
SSINS/sky_subtract.py
SSINS/tests/test_SS.py
docs/tutorial.rst

This PR updates `SS.write` so that it handles baselines independently from one another (catching it up with `SS.diff`). It also adds a couple tutorials.

Writing update

---

scripts/MWA_EoR_High_Flag.py

This is the simplest possible way to maybe resolve the issue that crops up when running multithreaded. The change is that the lone global variable has been renamed to possibly resolve a conflict there.
Don't merge this unless it's been tested.

remove mp from highflag script

---

SSINS/incoherent_noise_spectrum.py
SSINS/match_filter.py
SSINS/tests/test_MF.py
SSINS/tests/test_util.py
SSINS/util.py
docs/tutorial.rst
scripts/MWA_vis_to_SSINS.py

This PR adds an occupancy calculator function in util. It also changes events from tuples to namedtuples, which is a nice touch.

Add occ calculator

---

SSINS/plot_lib.py
SSINS/util.py

Fixes the missing arguments for `image_plot()` in the in-code documentation. There is a couple extra non-documentation clarification comments as well in `image_plot()`.
There are no actual code changes in this PR, so no code testing in particular should be needed.

augment plot_lib image_plot() arg docs, misc doc fixes

---

SSINS/Catalog_Plot.py
SSINS/tests/test_plot.py

This PR makes it so that when doing Catalog_Plot, there is a choice of matplotlib backend, instead of forcing "Agg".

Optional backend

---

.travis.yml

This pull request replaces #71 and also updates the python testing matrix to include python 3.8.

Update travis OS to 20.04 (focal) & update travis python checks

---

CHANGELOG.md
SSINS/Catalog_Plot.py
SSINS/match_filter.py
SSINS/sky_subtract.py
SSINS/tests/test_SS.py

This PR just fixes comparisons against string literals using "is" which can be problematic.

Remove "is" comparison against string literals.

---

SSINS/Catalog_Plot.py
SSINS/plot_lib.py
SSINS/tests/test_plot.py

This PR affects `image_plot`, `INS_plot` and the unit testing. It adds an option for extent to consider LSTs as an input mainly. It also replaces some string substitutions with formatted strings in the unit testing along with some adjustments to the unit tests to cover the new code. Finally, it changes the default colormap on `image_plot`.

Plot revamp

---

.github/testsuite.yml
README.md
ci/SSINS_tests.yml

Add the basic GitHub Actions stuff

GitHub actions

---

SSINS/plot_lib.py

This just pipes the `extend` and `alpha` keywords to `plot_lib.image_plot`

Image plot extend keyword

---

CHANGELOG.md
scripts/Run_HERA_SSINS.py

Let Run_HERA_SSINS.py take set of bad antennas to exclude

---

docs/tutorial.rst

Add some necessary info in an INS tutorial
This adds a missing and necessary code line and an additional comment in the "applying flags from an INS object" section of the tutorial.

Add missing line in tutorial

---

CHANGELOG.md
README.md
SSINS/sky_subtract.py
SSINS/tests/test_SS.py

Just changing my email in the readme
:)

Change email

---

scripts/Run_HERA_SSINS.py

Add `import hdf5plugin` for handle new correlator files with bitshuffle

---

CHANGELOG.md
SSINS/sky_subtract.py

Fixes an issue where optional parameters would result in an error if they were filled with None.
Make the check during diff ask if the attribute exists and is not None. This should be compatible across versions of pyuvdata and across data/metadata-only reads.

Pc app dec fix
